Repository AdoptOpenJDK/openjdk-website, pull requests merged in 2020-04, with the labels that each got.

#697 Add dedicated OpenJFX FAQ
  src/handlebars/faq.handlebars
Labels: TSC-Agenda

#700 allow website to show ea builds
  src/handlebars/releases.handlebars
  src/js/common.js
  src/js/releases.js
  src/scss/styles-4-releases.scss
Labels: enhancement

#702 Add release banner
  src/handlebars/partials/header.handlebars
Labels: enhancement

#704 show correct nightly binary type
  src/js/nightly.js
Labels: bug

#705 update wording for Packet
  src/handlebars/sponsors.handlebars
Labels: enhancement

#706 Improve Nightly Search Page
  src/handlebars/nightly.handlebars
  src/js/archive.js
  src/js/common.js
  src/js/installation.js
  src/js/nightly.js
  src/js/upstream.js
Labels: enhancement

#709 add EA tag to archive page
  src/handlebars/archive.handlebars
  src/js/archive.js
Labels: bug

#713 Release notes and show hide buttons
  package-lock.json
  package.json
  src/handlebars/partials/footer.handlebars
  src/handlebars/release_notes.handlebars
  src/js/common.js
  src/scss/styles-1-large-main.scss
Labels: enhancement

#715 add help me choose box to all pages
  src/handlebars/archive.handlebars
  src/handlebars/nightly.handlebars
  src/handlebars/releases.handlebars
Labels: bug
