Repository AdoptOpenJDK/openjdk-website, pull requests merged in 2021-02, with the labels that each got.

#898 Replaced append() with appendChild() to fix IE11 incompatibility (fixes #897)
  src/js/releases.js
Labels: bug

#891 german flyer added
  src/assets/adopt-flyer-de.pdf
  src/assets/adopt-flyer.pdf
  src/assets/flyer-preview.png
Labels: enhancement

#909 JMC 8.x snapshot build links
  src/handlebars/jmc.handlebars
Labels: enhancement

#911 Adds final JMC 8.0.0
  src/handlebars/jmc.handlebars
Labels: HTML, enhancement
